### ISSUE TITLE
Automated deployment to the cloud

### ISSUE THREAD

**Issue by siruslan** [xeb/fastText-docker#2]
Hi, is there any interest for an automated deployment to Jelastic cloud by a click? 
There are couple examples how it looks like at the repo (please see **Deployment** section)
https://github.com/PokemonGoMap/PokemonGo-Map
https://github.com/amoruga/git-push-deploy/tree/w/o-auth

And an example of the installation dialog inside (depends on the docker image specifics) 
<img src="https://raw.githubusercontent.com/sych74/PokemonGo-Map-in-Cloud/master/images/pokemap-installation-in-jelastic.png">

Thanks

**Comment by xeb** [comment]
I like the idea of providing out-of-the-box examples of running fastText in production containerized environments if others think it is valuable.  I haven't used Jelastic specifically.  Perhaps we can make a folder with example configurations & then accept PRs to add different ones.

Specifically examples for:
- Kubernetes
- Docker Swarm
- Mesos Marathon

Most of these will likely look similar since the binary container for fastText is extremely minimal.  How others use it will be interesting.  I don't know if anyone is working on a "TensorFlow Serving"-like component for fastText...

**Comment by siruslan** [comment]
Ok, I added an example how to deploy to Jelastic. I hope someone can add examples for the rest.

**Comment by xeb** [comment]
Closed by PR#1

**Comment by xeb** [comment]
I added some kubernetes examples & moved them both into a separate directory.  Feel free to submit a README.md for the Jelastic example if you'd like!  I kept the deploy button on the front README.md.

**Comment by siruslan** [comment]
Nice readme for kubernetes! I will add for jelastic as well.
